### ISSUE TITLE
Websocket port is not released on shutdown

### ISSUE THREAD

**Issue by goergch** [IUNO-TDM/PumpControl#11]
it should be released but isn't. Check the reason and fix

**Comment by goergch** [comment]
Sometimes the listening socket is closed correctly. But mostly it will take some time, until the port is reusable. 
The implementation is already checked and normally the shutdown methods should stop the websocket library correctly and the socket should be closed.

**Comment by bockha** [comment]
Please add more details to bug report since I can not reproduce this on a pumpcontrol running standalone.
